# Generated by Django 2.0.3 on 2018-03-08 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=100)),
                ('book_pubdate', models.DateField()),
                ('book_summary', models.TextField()),
                ('book_country', models.CharField(max_length=100)),
                ('book_link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='writer',
            fields=[
                ('writer_id', models.AutoField(primary_key=True, serialize=False)),
                ('writer_name', models.CharField(max_length=100)),
                ('writer_dob', models.DateField()),
                ('writer_dod', models.DateField(blank=True, null=True, verbose_name='died')),
                ('writer_contact', models.CharField(max_length=100)),
                ('writer_bio', models.TextField()),
                ('writer_image', models.ImageField(blank=True, upload_to='static/images')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='bwriter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryApp.writer'),
        ),
    ]
