# Generated by Django 2.0 on 2018-03-06 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='link',
            field=models.CharField(help_text='Enter a link of the book', max_length=200),
        ),
    ]
