# Generated by Django 2.0 on 2018-03-06 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0003_auto_20180306_0207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='writer',
            options={'ordering': ['first_name', 'last_name']},
        ),
    ]
