# Generated by Django 2.0.3 on 2018-03-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='writer_image',
            field=models.ImageField(blank=True, upload_to='libraryApp/static/images'),
        ),
    ]
